const FORBIDDEN_REEL_SCRIPT_KEYS = new Set([
  "clientId",
  "client_id",
  "strategyId",
  "strategy_id",
  "providerKey",
  "provider_key",
  "tier",
  "envKeyName",
  "model",
  "status",
  "approved",
  "mustDiscloseNotOwner",
  "must_disclose_not_owner",
  "ruleFlags",
  "hook",
  "body",
  "cta",
  "onScreenText",
  "voiceoverText",
  "on_screen_text",
  "voiceover_text",
  "targetDurationSec",
  "brollBeats",
  "coldOpenNotes",
  "editingNotes",
  "brief",
  "modalidad",
  "invokedBy",
  "role",
  "auth_user_id",
  // US-5.2: threshold smuggle keys — readability limits are server-frozen
  "maxCharsPerBeat",
  "maxCharsPerBeatLine",
  "wordsPerSecond",
  "wordsPerSecondTarget",
  "thresholds",
  "readabilityConfig",
  "readability",
  "maxBeatLinesTotal",
  "maxLinesPerBeat",
  "voWarnOverRatio",
  "voWarnUnderRatio",
  // US-7.1: budget authority keys — use budgetOverride / overrideReason only
  "maxCostCents",
  "max_cost_cents",
  "providerTier",
  "provider_tier",
  "estimatedCostCents",
  "estimated_cost_cents",
  "cumulativeCostCents",
  "cumulative_cost_cents",
  "budgetCap",
  "policyId",
  "policy_id",
  "rules",
  "skipBudgetCheck",
  "skip_budget_check",
  "overrideBudget",
  "override_budget",
  "confirmGeneration",
  "confirm_generation",
]);

export function findForbiddenReelScriptKeys(raw: unknown): string[] {
  if (raw === null || typeof raw !== "object" || Array.isArray(raw)) {
    return [];
  }
  return Object.keys(raw).filter((key) => FORBIDDEN_REEL_SCRIPT_KEYS.has(key));
}
